### ISSUE TITLE
admin dashboard: Create class design is different from the design

### ISSUE THREAD

**Issue by techstudioconsults** [techstudioconsults/Techstudio-site#53]

**Comment by techstudioconsults** [comment]
please i need more details for this issue from the observer

**Comment by Enkaay** [comment]
The preference is showing the day of the week the class is meant to commence instead of indicating if it's an online, weekday or weekend class

**Comment by techstudioconsults** [comment]
No it is not, the preference is indicating online, weekday and weekend
![Screenshot 2023-04-20 115558](https://user-images.githubusercontent.com/122175536/233345906-5396f5d7-3073-4dda-a50e-8a64c7d43e40.png)
