### ISSUE TITLE
The View Lesson/New lesson button should be disabled if a class hasn't been created.

### ISSUE THREAD

**Issue by Enkaay** [techstudioconsults/Techstudio-site#78]

**Comment by techstudioconsults** [comment]
This issue has been resolved.
![Screenshot 2023-04-27 001206](https://user-images.githubusercontent.com/122175536/234722014-38b91326-cf93-4ae3-b4fb-9850d7cea118.png)
![Screenshot 2023-04-27 001240](https://user-images.githubusercontent.com/122175536/234722017-f8718a01-7954-46d1-a195-60ca29cff9fb.png)
