### ISSUE TITLE
Inconsistent View of Classes

### ISSUE THREAD

**Issue by Enkaay** [techstudioconsults/Techstudio-site#80]
When you have two classes
![image](https://user-images.githubusercontent.com/129671421/234120376-dec6135d-7f8b-4599-93b1-1209b4f47af1.png)

When you have one class

![image](https://user-images.githubusercontent.com/129671421/234120430-040d9eae-aedd-45ad-9a15-d8c99cbc13d6.png)

**Comment by techstudioconsults** [comment]
fixed
